/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as IndexRouteImport } from "./app/index";
import { Route as RunsRunIdRouteImport } from "./app/runs.$runId";
import { Route as RunsRunIdIndexRouteImport } from "./app/runs.$runId.index";
import { Route as RunsRunIdFilesRouteImport } from "./app/runs.$runId.files";
import { Route as RunsRunIdChaptersChapterNumberRouteImport } from "./app/runs.$runId.chapters.$chapterNumber";
import { Route as PrOwnerRepoNumberRouteImport } from "./app/pr.$owner.$repo.$number";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => rootRouteImport,
} as any);
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => RunsRunIdRoute,
} as any);
const RunsRunIdFilesRoute = RunsRunIdFilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => RunsRunIdRoute,
} as any);
const RunsRunIdChaptersChapterNumberRoute =
  RunsRunIdChaptersChapterNumberRouteImport.update({
    id: "/chapters/$chapterNumber",
    path: "/chapters/$chapterNumber",
    getParentRoute: () => RunsRunIdRoute,
  } as any);
const PrOwnerRepoNumberRoute = PrOwnerRepoNumberRouteImport.update({
  id: "/pr/$owner/$repo/$number",
  path: "/pr/$owner/$repo/$number",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/runs/$runId": typeof RunsRunIdRouteWithChildren;
  "/runs/$runId/files": typeof RunsRunIdFilesRoute;
  "/runs/$runId/": typeof RunsRunIdIndexRoute;
  "/pr/$owner/$repo/$number": typeof PrOwnerRepoNumberRoute;
  "/runs/$runId/chapters/$chapterNumber": typeof RunsRunIdChaptersChapterNumberRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/runs/$runId/files": typeof RunsRunIdFilesRoute;
  "/runs/$runId": typeof RunsRunIdIndexRoute;
  "/pr/$owner/$repo/$number": typeof PrOwnerRepoNumberRoute;
  "/runs/$runId/chapters/$chapterNumber": typeof RunsRunIdChaptersChapterNumberRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/runs/$runId": typeof RunsRunIdRouteWithChildren;
  "/runs/$runId/files": typeof RunsRunIdFilesRoute;
  "/runs/$runId/": typeof RunsRunIdIndexRoute;
  "/pr/$owner/$repo/$number": typeof PrOwnerRepoNumberRoute;
  "/runs/$runId/chapters/$chapterNumber": typeof RunsRunIdChaptersChapterNumberRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/runs/$runId"
    | "/runs/$runId/files"
    | "/runs/$runId/"
    | "/pr/$owner/$repo/$number"
    | "/runs/$runId/chapters/$chapterNumber";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/runs/$runId/files"
    | "/runs/$runId"
    | "/pr/$owner/$repo/$number"
    | "/runs/$runId/chapters/$chapterNumber";
  id:
    | "__root__"
    | "/"
    | "/runs/$runId"
    | "/runs/$runId/files"
    | "/runs/$runId/"
    | "/pr/$owner/$repo/$number"
    | "/runs/$runId/chapters/$chapterNumber";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren;
  PrOwnerRepoNumberRoute: typeof PrOwnerRepoNumberRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs/$runId": {
      id: "/runs/$runId";
      path: "/runs/$runId";
      fullPath: "/runs/$runId";
      preLoaderRoute: typeof RunsRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs/$runId/": {
      id: "/runs/$runId/";
      path: "/";
      fullPath: "/runs/$runId/";
      preLoaderRoute: typeof RunsRunIdIndexRouteImport;
      parentRoute: typeof RunsRunIdRoute;
    };
    "/runs/$runId/files": {
      id: "/runs/$runId/files";
      path: "/files";
      fullPath: "/runs/$runId/files";
      preLoaderRoute: typeof RunsRunIdFilesRouteImport;
      parentRoute: typeof RunsRunIdRoute;
    };
    "/runs/$runId/chapters/$chapterNumber": {
      id: "/runs/$runId/chapters/$chapterNumber";
      path: "/chapters/$chapterNumber";
      fullPath: "/runs/$runId/chapters/$chapterNumber";
      preLoaderRoute: typeof RunsRunIdChaptersChapterNumberRouteImport;
      parentRoute: typeof RunsRunIdRoute;
    };
    "/pr/$owner/$repo/$number": {
      id: "/pr/$owner/$repo/$number";
      path: "/pr/$owner/$repo/$number";
      fullPath: "/pr/$owner/$repo/$number";
      preLoaderRoute: typeof PrOwnerRepoNumberRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdFilesRoute: typeof RunsRunIdFilesRoute;
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute;
  RunsRunIdChaptersChapterNumberRoute: typeof RunsRunIdChaptersChapterNumberRoute;
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdFilesRoute: RunsRunIdFilesRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
  RunsRunIdChaptersChapterNumberRoute: RunsRunIdChaptersChapterNumberRoute,
};

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  PrOwnerRepoNumberRoute: PrOwnerRepoNumberRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
